name: Tests CI
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: dart analyze --fatal-infos

  test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test -p chrome,vm,node --compiler kernel,dart2wasm,dart2js --test-randomize-ordering-seed=random
